apiVersion: v1
kind: Service

metadata:
  name: llm-runtime
  namespace: ai-workloads

  labels:
    app.kubernetes.io/name: llm-runtime
    app.kubernetes.io/component: inference-runtime
    app.kubernetes.io/part-of: ai-platform

spec:
  type: ClusterIP

  ports:
    - name: vllm
      protocol: TCP
      port: 8000
      targetPort: 8000

    - name: llama-cpp
      protocol: TCP
      port: 8081
      targetPort: 8081

---

apiVersion: discovery.k8s.io/v1
kind: EndpointSlice

metadata:
  name: llm-runtime-external
  namespace: ai-workloads

  labels:
    kubernetes.io/service-name: llm-runtime
    app.kubernetes.io/name: llm-runtime
    app.kubernetes.io/component: inference-runtime
    app.kubernetes.io/part-of: ai-platform

addressType: IPv4

ports:
  - name: vllm
    protocol: TCP
    port: 8000

  - name: llama-cpp
    protocol: TCP
    port: 8081

endpoints:
  - addresses:
      - "192.168.64.1"

    conditions:
      ready: true
