from __future__ import annotations

import time

from kubernetes import client

from app.core.config import get_settings
from app.services.kubernetes_service import KubernetesService


POD_NAME = "model-delivery-runtime-test"

MODEL_REFERENCE = (
    "registry.secure-ai.local:5000/"
    "ai-models-trusted/qwen3-0.6b"
    "@sha256:"
    "0d5a6a40e734feff221f1ad1334c29df"
    "c29c55ec1b82d3ad2149b745fd4cb363"
)

MODEL_PATH = "/models/model"

REGISTRY_SECRET = "ai-model-registry-credentials"


def main() -> None:
    settings = get_settings()

    kubernetes_service = KubernetesService(
        namespace=settings.kubernetes_namespace,
        mode=settings.kubernetes_mode,
    )

    core_api = kubernetes_service.core_api

    # ======================================================
    # CLEAN PREVIOUS TEST
    # ======================================================

    try:
        core_api.delete_namespaced_pod(
            name=POD_NAME,
            namespace=settings.kubernetes_namespace,
        )

        print(
            f"Previous Pod '{POD_NAME}' deleted."
        )

        time.sleep(2)

    except client.ApiException as exc:
        if exc.status != 404:
            raise

    # ======================================================
    # INIT CONTAINER
    #
    # Reuse exactly the model puller generated by
    # KubernetesService.
    # ======================================================

    model_puller = (
        kubernetes_service._build_model_puller(
            model_artifact_reference=MODEL_REFERENCE,
            model_mount_path=MODEL_PATH,
            registry_secret_name=REGISTRY_SECRET,
            registry_insecure=True,
        )
    )

    # ======================================================
    # RUNTIME VALIDATION CONTAINER
    #
    # No vLLM.
    # No NVIDIA GPU.
    #
    # It simply verifies that the files produced by the
    # initContainer are available through the shared volume.
    # ======================================================

    runtime_validator = client.V1Container(
        name="runtime-validator",

        image="busybox:1.36",

        image_pull_policy="IfNotPresent",

        command=[
            "/bin/sh",
            "-c",
        ],

        args=[
            """
set -eu

echo "=== RUNTIME MODEL HANDOFF TEST ==="

echo "Checking model directory..."

ls -lh /models/model

echo ""
echo "Checking required runtime files..."

test -f /models/model/model.safetensors
echo "model.safetensors OK"

test -f /models/model/config.json
echo "config.json OK"

test -f /models/model/tokenizer.json
echo "tokenizer.json OK"

test -f /models/model/tokenizer_config.json
echo "tokenizer_config.json OK"

test -f /models/model/trusted-manifest.json
echo "trusted-manifest.json OK"

echo ""
echo "Model storage is readable by runtime."

echo "=== RUNTIME HANDOFF SUCCESS ==="
"""
        ],

        volume_mounts=[
            client.V1VolumeMount(
                name="model-storage",
                mount_path=MODEL_PATH,
                read_only=True,
            )
        ],

        security_context=(
            client.V1SecurityContext(
                allow_privilege_escalation=False,
                run_as_non_root=True,
                run_as_user=10001,
                run_as_group=10001,
                read_only_root_filesystem=True,
                capabilities=(
                    client.V1Capabilities(
                        drop=["ALL"]
                    )
                ),
            )
        ),

        resources=(
            client.V1ResourceRequirements(
                requests={
                    "cpu": "50m",
                    "memory": "64Mi",
                },
                limits={
                    "cpu": "200m",
                    "memory": "128Mi",
                },
            )
        ),
    )

    # ======================================================
    # VOLUMES
    # ======================================================

    model_volume = client.V1Volume(
        name="model-storage",
        empty_dir=(
            client.V1EmptyDirVolumeSource(
                size_limit="5Gi"
            )
        ),
    )

    oras_home_volume = client.V1Volume(
        name="oras-home",
        empty_dir=(
            client.V1EmptyDirVolumeSource()
        ),
    )

    # ======================================================
    # POD
    # ======================================================

    pod = client.V1Pod(
        api_version="v1",
        kind="Pod",

        metadata=client.V1ObjectMeta(
            name=POD_NAME,
            namespace=settings.kubernetes_namespace,

            labels={
                "app": POD_NAME,
                "managed-by": "ai-control-plane-test",
                "purpose": "model-delivery-validation",
            },
        ),

        spec=client.V1PodSpec(
            restart_policy="Never",

            automount_service_account_token=False,

            # Lab-only DNS mapping.
            host_aliases=[
                client.V1HostAlias(
                    ip="192.0.2.203",
                    hostnames=[
                        "registry.secure-ai.local"
                    ],
                )
            ],

            init_containers=[
                model_puller
            ],

            containers=[
                runtime_validator
            ],

            volumes=[
                model_volume,
                oras_home_volume,
            ],

            security_context=(
                client.V1PodSecurityContext(
                    run_as_non_root=True,

                    seccomp_profile=(
                        client.V1SeccompProfile(
                            type="RuntimeDefault"
                        )
                    ),
                )
            ),
        ),
    )

    # ======================================================
    # CREATE
    # ======================================================

    print(
        "Creating model delivery validation Pod..."
    )

    core_api.create_namespaced_pod(
        namespace=settings.kubernetes_namespace,
        body=pod,
    )

    print(
        f"Pod created: {POD_NAME}"
    )

    print()
    print(
        "Watch with:"
    )
    print(
        f"kubectl get pod -n "
        f"{settings.kubernetes_namespace} "
        f"{POD_NAME} -w"
    )

    print()
    print(
        "InitContainer logs:"
    )
    print(
        f"kubectl logs -n "
        f"{settings.kubernetes_namespace} "
        f"{POD_NAME} -c model-puller"
    )

    print()
    print(
        "Runtime logs:"
    )
    print(
        f"kubectl logs -n "
        f"{settings.kubernetes_namespace} "
        f"{POD_NAME} -c runtime-validator"
    )


if __name__ == "__main__":
    main()
