apiVersion: v1
kind: LimitRange
metadata:
  name: ai-workloads-limits
  namespace: ai-workloads
spec:
  limits:
    - type: Container

      defaultRequest:
        cpu: "100m"
        memory: 128Mi

      default:
        cpu: "500m"
        memory: 512Mi

      max:
        cpu: "4"
        memory: 8Gi

      min:
        cpu: "50m"
        memory: 64Mi
