# ==========================================================
# MODEL INGESTION
# ==========================================================

apiVersion: v1
kind: ServiceAccount

metadata:
  name: model-ingestion
  namespace: ai-workloads

  labels:
    app.kubernetes.io/name: model-ingestion
    app.kubernetes.io/component: model-security-pipeline
    app.kubernetes.io/part-of: ai-platform

automountServiceAccountToken: false

---

# ==========================================================
# MODEL PROMOTION
# ==========================================================

apiVersion: v1
kind: ServiceAccount

metadata:
  name: model-promotion
  namespace: ai-workloads

  labels:
    app.kubernetes.io/name: model-promotion
    app.kubernetes.io/component: model-security-pipeline
    app.kubernetes.io/part-of: ai-platform

automountServiceAccountToken: false

---

# ==========================================================
# RUNTIME ACTIVATION
# ==========================================================

apiVersion: v1
kind: ServiceAccount

metadata:
  name: runtime-activation
  namespace: ai-workloads

  labels:
    app.kubernetes.io/name: runtime-activation
    app.kubernetes.io/component: runtime-orchestrator
    app.kubernetes.io/part-of: ai-platform

automountServiceAccountToken: false

---

# ==========================================================
# AI INFERENCE RUNTIME
# ==========================================================

apiVersion: v1
kind: ServiceAccount

metadata:
  name: ai-runtime
  namespace: ai-workloads

  labels:
    app.kubernetes.io/name: ai-runtime
    app.kubernetes.io/component: inference-runtime
    app.kubernetes.io/part-of: ai-platform

automountServiceAccountToken: false
