apiVersion: v1
kind: Secret

metadata:
  name: ai-control-plane-secrets
  namespace: ai-system

type: Opaque

stringData:

  ACP_DATABASE_URL: >-
    postgresql+psycopg://ai_platform:CHANGE_ME@postgres.ai-system.svc.cluster.local:5432/ai_platform

  ACP_JWT_SECRET_KEY: >-
    CHANGE_ME_WITH_A_RANDOM_64_CHAR_SECRET

  ACP_VLLM_API_KEY: >-
    CHANGE_ME

  ACP_REGISTRY_USERNAME: >-
    CHANGE_ME

  ACP_REGISTRY_PASSWORD: >-
    CHANGE_ME
