apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ai-control-plane
  namespace: ai-workloads
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - create
      - delete

  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list

  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - get
      - list
      - create
      - delete
