apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: ai-platform-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.64.240-192.168.64.250

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: ai-platform-l2
  namespace: metallb-system
spec:
  ipAddressPools:
    - ai-platform-pool
