apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: zot-registry
  namespace: registry
spec:
  secretName: zot-registry-tls

  dnsNames:
    - registry.andrick.local

  issuerRef:
    name: selfsigned-cluster-secure-ai
    kind: ClusterIssuer
