apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: grafana
  namespace: monitoring
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"

spec:
  ingressClassName: nginx

  tls:
    - hosts:
        - grafana.ai.local
      secretName: grafana-tls

  rules:
    - host: grafana.ai.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ai-monitoring-grafana
                port:
                  number: 80
