"""create deployments table

Revision ID: f50f72fdd7bd
Revises: 
Create Date: 2026-08-10 17:56:19.893434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f50f72fdd7bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deployments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=63), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('repository', sa.String(length=512), nullable=False),
    sa.Column('profile', sa.String(length=255), nullable=False),
    sa.Column('runtime', sa.String(length=255), nullable=False),
    sa.Column('deployment_mode', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('endpoint', sa.String(length=1024), nullable=True),
    sa.Column('model_artifact_reference', sa.Text(), nullable=False),
    sa.Column('model_artifact_digest', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deployments_name'), 'deployments', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deployments_name'), table_name='deployments')
    op.drop_table('deployments')
    # ### end Alembic commands ###
